# https://taskfile.dev

version: "3"

dotenv: ['.env', '{{.ENV}}/.env.', '{{.HOME}}/.env']

tasks:
  build:
    summary: |
      Create a production build of the application. The final build
      will embed the frontend app as well.
    deps:
      - frontend:build
    dir: backend/
    cmds:
      - go build -tags=nomsgpack .
      - mkdir -p ../artifacts
      - mv webhooks ../artifacts/skirthooks

  dev:
    deps:
      - frontend:dev
      - backend:dev
    

  frontend:install_deps:
    dir: frontend/
    cmds:
      - npm install

  frontend:build:
    deps:
      - frontend:install_deps
    dir: frontend/
    cmds:
      - npm run build

  frontend:dev:
    dir: frontend/
    deps:
      - frontend:install_deps
    cmds:
      - npm run dev

  backend:dev:
    deps:
      - frontend:build
    dir: backend/
    sources:
      - backend/**/*.*
    cmds:
      - go run .